version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_app:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./files:/usr/src/files
    command: "celery -A app.celery_app.tasks worker -l info -P gevent"

  flower-celery:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    command: "celery -A app.celery_app.tasks flower --port=5555"

  api:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./files:/usr/src/files
    command: "uvicorn app.main:app --host=0.0.0.0 --port=8000"
